# makefile for mac os x
#
# use homebrew to install libxml2
#   brew install libxml2
#
# I think libcurl is already there on os x

pubmed: pubmed.c
        gcc --std=c99 -Wall pubmed.c -lxml2 -lcurl -I/usr/local/opt/libxml2/include/libxml2 -o pubmed
